apiVersion: v1
kind: Pod
metadata:
  name: hairsalon
  labels:
    app: hairsalon
spec:
  restartPolicy: OnFailure
  containers:

    - name: api
      image: localhost/hairsalon-api:latest
      imagePullPolicy: Never
      ports:
        - containerPort: 8080
          hostPort: 5000
      env:
        - name: ASPNETCORE_ENVIRONMENT
          value: Development
        - name: ConnectionStrings__sqlite
          value: Data Source=/app/data/hair.db
        - name: AllowedHosts
          value: "*"
        - name: Cors__AllowedOrigins__0
          value: http://localhost:3000
        - name: Cors__AllowedOrigins__1
          value: http://localhost
      volumeMounts:
        - name: api-data
          mountPath: /app/data

    - name: web
      image: localhost/hairsalon-web:latest
      imagePullPolicy: Never
      ports:
        - containerPort: 80
          hostPort: 3000

  volumes:
    - name: api-data
      hostPath:
        path: /var/lib/hairsalon/data
        type: DirectoryOrCreate
